### ISSUE TITLE
need example of running a test

### ISSUE THREAD

**Issue by lmj0011** [thetutlage/japa#1]
I see the examples, but what would the command look like when running a test with japa?

I assume: `$ japa test1.js`

Seems like this should be right after:
https://github.com/thetutlage/japa#installation

**Comment by RomainLanz** [comment]
Hey @lmj0011 !

You need to use `node` directly to run your test.

You have an example in this repository: https://github.com/Slynova-Org/node-fence

**Comment by lmj0011** [comment]
@RomainLanz 

Thanks for the examples
PS. I have no clue what that package you linked, is suppose to do.

**Comment by RomainLanz** [comment]
Yeah I need to finish it and write the documentation for it but I haven't free time atm :(

**Comment by thetutlage** [comment]
@lmj0011 You just need to run the test file using node 

```
node test1.js 
```
