### ISSUE TITLE
JUnit or xUnit 2 Test Results

### ISSUE THREAD

**Issue by zanechua** [thetutlage/japa#11]
## Description

Are there any plans on adding JUnit or xUnit Reports to japa? This will allow us to display some statistics about each particular test that has passed or failed in certain CI/CD pipelines. Notably Azure Dev Ops Pipelines is one of them.

I noticed that in the main documentation you worded that the results were displayed with the "default" `list` reporter, so I am assuming that there is a way to provide an alternate reporter that will be able to generate out the results in the relevant format?

**Comment by thetutlage** [comment]
I am not very much familiar with `JUnit` or `xUnit`. Can you please share some links or more about them in general? I will be happy to add them (if it makes sense) :)

**Comment by zanechua** [comment]
Here's some info about them:

JUnit
https://llg.cubic.org/docs/junit/

xUnit
https://xunit.net/docs/format-xml-v2.html

**Comment by thetutlage** [comment]
Thanks for the links, I believe this requires lots of reading and currently, I don't have the bandwidth for same.

I will look into it later sometime or you can share a PR for adding them

**Comment by zanechua** [comment]
@thetutlage I actually have a reporter ready to output the junit format.

However this is pegged to the v1.0.3, will you accept PRs for that outdated version?

**Comment by thetutlage** [comment]
Is their any reason, you have it for the outdated version?

**Comment by zanechua** [comment]
Sorry. I meant to say `v1.0.6` not `v1.0.3`. We're still using `adonis-vow` and that depends on the `v1.0.6` version of the package.

**Comment by zanechua** [comment]
I've cleaned up the work a little and made it available here:

https://github.com/zanechua/japa/tree/v106-junit-xunit

**Comment by mjclemente** [comment]
@zanechua did you considering sharing a PR from your fork?

**Comment by zanechua** [comment]
The code is available via that tree but only for `v1.0.6`. You're welcome to take the code and update it to typescript.

**Comment by mjclemente** [comment]
ahhh. Got it. Thanks.

**Comment by fareeda0** [comment]
Apologies for resurrecting this 😅

Turns out I ran into the exact same use case. I think this would be a super useful feature to have.

@zanechua I tried the link you provided but it seems it's no longer available.

If you still have the code, I'd be happy to pick this up.

**Comment by zanechua** [comment]
@fareeda0

I probably removed it when I was clearing up repos. I've moved on from Adonis as it didn't provide enough support for my CI/CD use cases.

I don't have a copy of the code I updated but my colleague at the point of time wrote the initial bunch of it which you can find:

https://github.com/zhiichengg/japa/commit/edf0bd105f6520f02b96f2ee252caf9d20c689a5

Cheers.
