### ISSUE TITLE
Allow to put Node.js flags in the payload of configure ?

### ISSUE THREAD

**Issue by fraxken** [thetutlage/japa#12]
## Description

Hi, i'm working on a experimental branch to switch over ESM on one of my project. But my test fail because i use japa.configure to run multiple tests with multiple files (because ESM is still under a flag ... so the new syntax fail)

Can you allow to put Node.js flags in the payload of configure ?

Example:
```js
japa.configure({
    flags: ["--experimental-modules"],
    files: [
        // join(__dirname, "communication.js"),
        // join(__dirname, "utils.js"),
        // join(__dirname, "test.js"),
        join(__dirname, "wca.js")
    ]
});
```

## Package version
2.0.10

Best Regards,
Thomas

**Comment by thetutlage** [comment]
Can you share in which file you put this `japa.configure` statement?

**Comment by fraxken** [comment]
Hi,

The repository is open: https://github.com/SlimIO/Core/blob/master/test/japaRunner.js

I run this with npm test:
`"test": "node --experimental-modules test/japaRunner.js"`

The error:
```
F:\Code\SlimIO\Core\test\wca.js:2
import { join, dirname } from "path";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at F:\Code\SlimIO\Core\node_modules\japa\build\src\SlimRunner\index.js:52:35
    at Array.forEach (<anonymous>)
    at Object.run (F:\Code\SlimIO\Core\node_modules\japa\build\src\SlimRunner\index.js:52:17)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Best Regards,
Thomas

**Comment by thetutlage** [comment]
I believe it has to do the way Japa internally require files using `commonjs` syntax.

Can you also pass ` --es-module-specifier-resolution=node` flag?

If that doesn’t work, then I have look more into esm modules, since I haven’t played with them yet

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter

**Comment by arbassic** [comment]
For those, who struggle with a similar issue:

```typescript
import japa from 'japa';

japa.configure({
  files: ['test/*.ts'],
  experimentalEsmSupport: true, // « add this line
});
```
