### ISSUE TITLE
Set default timeout for all tests

### ISSUE THREAD

**Issue by otang** [thetutlage/japa#14]
## Description

I would like to change the default timeout for all my tests. This saves me from having to manually edit the timeout for each test. The database I am testing on is very slow and as a result all my tests take long to complete however this is not an error it's the expected behaviour.

**Comment by thetutlage** [comment]
Will this help? https://github.com/thetutlage/japa/blob/develop/README.md#configure-options

**Comment by otang** [comment]
@thetutlage yes it's helpful. I'm using adonis so I need to find a way to configure this via adonis' testing framework, Vow. Given the japa instance is it possible to access the current configuration? I want to augment it and change one value instead of replacing it

**Comment by otang** [comment]
I was able to accomplish this via the "-t" CLI argument
