### ISSUE TITLE
can't get Japa to work with new version of Adonis 5

### ISSUE THREAD

**Issue by pikitgb** [thetutlage/japa#17]
Hi guys, 
i just installed japa to write some tests for my repositories/service classes
I'm getting this error while trying to run with node.

![image](https://user-images.githubusercontent.com/2738018/82103162-08a39380-96e0-11ea-8ef9-f80ce2b6ddb5.png)

**Comment by thetutlage** [comment]
With the provided information, all I can do is nothing?

**Comment by pikitgb** [comment]
my bad @thetutlage, will provide extra information. Thanks
