### ISSUE TITLE
Possible to gather test coverage?

### ISSUE THREAD

**Issue by patwhite** [thetutlage/japa#19]
### Description

I really like the framework and the simplicity - currently use jest, the only thing I’m unclear on is how to gather test coverage with Japa. Is that something that’s possible or unsupported?

**Comment by thetutlage** [comment]
You can using [nyc](https://www.npmjs.com/package/nyc). Following is a screenshot from one of my projects. 

<img width="789" alt="Screen Shot 2020-06-16 at 11 50 55 AM" src="https://user-images.githubusercontent.com/1706381/84738609-da0f2600-afc7-11ea-841c-09273cb29a56.png">

And following is the script in the `package.json` file.

```
{
  "scripts": {
    "test": "node japaFile.js",
    "coverage": "nyc npm run test"
  }
}
```

It works for Typescript files too

**Comment by patwhite** [comment]
Great, thanks!

**Comment by jlenon7** [comment]
Hey guys. Sorry for reopening this issue, but I think it might be useful for someone that is having problems using [nyc](https://www.npmjs.com/package/nyc) with Japa and ESM. At this moment nyc does not support ESM, the code coverage generated by him is always 0%. I really recommend using [c8](https://www.npmjs.com/package/c8) instead that works the "same way" of nyc and is compatible with ESM.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/52840235/165879332-bd2148fd-bf1f-4951-8fc3-9bd4f3f83d17.png">

**Comment by thetutlage** [comment]
Thanks for sharing. We have covered c8 in the docs as wellhttps://japa.dev/coverage#using-c8
