### ISSUE TITLE
How to test informations in headers ?

### ISSUE THREAD

**Issue by GustavoSMelo** [thetutlage/japa#22]
Hello, i am developing a test that search one user in database with base about id of this user, i am passing this information in headers
so.. how can i realize the test about it ?

because i can't find this information in docs

**Comment by thetutlage** [comment]
Japa is just a test runner (means its job is to just run the test functions) and what happens within the function is outside the scope of Japa.

Based upon the package you are using to make HTTP requests, you have to look into its docs to read the headers and write assertions for it

**Comment by GustavoSMelo** [comment]
Thanks for your reply dude, i got a little confused with this because i am started my studys about tests in this week,
but i love your project and i will use in my project
