### ISSUE TITLE
[Feature] Support global before each and after each

### ISSUE THREAD

**Issue by darklight9811** [thetutlage/japa#24]
## Description

I usually change a lot of things in my database during the tests, and placing the same beforeEach blocks in every test group is a little bit frustrating. I really would like to prepare auth, clean users, etc, before every test.

**Comment by thetutlage** [comment]
The readme does cover the global hooks. https://github.com/thetutlage/japa#runner-hooks

**Comment by darklight9811** [comment]
They support before and after, but do not support beforeEach and afterEach.

**Comment by thetutlage** [comment]
What will be the `each` in this case? You mean run before every group?

**Comment by SAGV** [comment]
Yes, this is super useful to automatically rollback db transactions and all the stubs after every test by default

**Comment by clabnet** [comment]
Are there news on this feature ?

**Comment by m-i-c-h-a-l** [comment]
This is supported, see https://japa.dev/docs/test-suites#configure-suite-groups-and-tests
