### ISSUE TITLE
Ace Command

### ISSUE THREAD

**Issue by hugoaboud** [thetutlage/japa#39]
I've followed the instructions on the [adonis cookbook](https://docs.adonisjs.com/cookbooks/testing-adonisjs-apps) to integrate `japa` with `AdonisJS` and it fits my needs really well.

I think one thing might me improved, though: the command for running the tests.

I've created an `ace command` for that, available below, so I'm able to run the tests with `node ace test` instead of `node -r @adonisjs/assembler/build/register japaFile.ts`.

`/commands/Test.ts`
```typescript
import { BaseCommand } from '@adonisjs/core/build/standalone'
import { execFile } from 'child_process'

export default class Test extends BaseCommand {

  public static commandName = 'test'
  public static description = 'Run all tests.'

  public static settings = {
    loadApp: false,
    stayAlive: true,
  }

  public async run () {
    const child = execFile('node', ['-r', '@adonisjs/assembler/build/register', 'japaFile.ts'], {
        env: {
            ...process.env,
            FORCE_COLOR: 'true',
        },
    });
    if (child.stdout) {
      child.stdout.on('data', function(data) {
        console.log(data.toString().trim()); 
      });
    }
  }
}
```

Please let me know if that's a valid approach, I'm able to make a pull request given some instructions (mainly on the currently not implemented `npm invoke`, I guess).

**Comment by thetutlage** [comment]
AdonisJS will have proper testing support. I will close this issue for now :)
