### ISSUE TITLE
Running multiple files does not work

### ISSUE THREAD

**Issue by Danicoco** [thetutlage/japa#45]
While running individual test works perfectly, I'm unable to run multiple test files. My test are written in .ts and setting up a index.js file to configure multiple test doesn't work.

### Content of index.js
`
require('ts-node').register();

const { configure } = require('japa');

configure({
  files: ['/*.ts'],
  experimentalEsmSupport: false,
});

`
**Note**
experimentalEsmSupport was set to both true and false and return the same result. On the command line. ZERO TESTS EXECUTED was printed.

## Package version
4.0.0

## Error Message & Stack Trace
ZERO TESTS EXECUTED Printed

**Comment by thetutlage** [comment]
Its because your files glob is incorrect. I assume you want to run all `.ts` file and the glob for that should be. 

```ts
files: ['**/*.ts']
```
