### ISSUE TITLE
Handling events on tick 1 (constructor) doesn't work

### ISSUE THREAD

**Issue by fraxken** [thetutlage/japa#7]
Hi,

**What i try to achieve** : 
I want to catch a event triggered on tick 0 (constructor most of the time so). This should be triggered on tick 1 (because of internal nextTick of events package). So when my test catch this event, it's done().

**The problem** :
I prepared a simple example to demonstrate you the problem 

```js
const test = require('japa');
const events = require('events');

class testJapa extends events {
    constructor() {
        super();
        this.emit('construct');
    }
}
let eventWrapper = new testJapa();

test('eventWrapper construct',function(assert,done) {
    eventWrapper.on('construct',function() {
        console.log('construct triggered!');
        done();
    });
});
```

Ok it's fail.

```
Error: Test timeout, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

I know, you are a good developer so the test handler has been nextTick to ensure asynchronous execution.

So i update my code for 
```js
constructor() {
    super();
    process.nextTick( () => {
        this.emit('construct');
    });
}
```

Result : **Same error as before* 

So i made some tests and decide to try this : 

```js
let eventWrapper;
setImmediate(() => {
    eventWrapper = new testJapa();
});
```

And no the error is : `TypeError: Cannot read property 'on' of undefined`

So we have to trigger a another event from the construct one (and the second will be catched, because he is on tick 2 now).

Waiting for your feedback on the subject.

Best Regards,
Thomas

**Comment by thetutlage** [comment]
I believe your event takes a bit more, mind setting a timeout on your test.

```js
test('eventWrapper construct',function(assert,done) {
    eventWrapper.on('construct',function() {
        console.log('construct triggered!');
        done();
    });
}).timeout(0)
```

**Comment by thetutlage** [comment]
Also there are some flaws with the original example u shared.

You instantiate the class outside of test, which emits the event write away and inside your test, the event is never emitted and thus `done` is never called.

**Comment by thetutlage** [comment]
In short this should work

```js
const test = require('japa');
const events = require('events');

class testJapa extends events {
}

test('eventWrapper construct',function(assert,done) {
   let eventWrapper = new testJapa();
    eventWrapper.on('construct',function() {
        console.log('construct triggered!');
        done();
    });
    eventWrapper.emit('construct');
});
```

**Comment by fraxken** [comment]
Hi,

Moving everything on the test scope effectively fix my original problem (my event was already fired in nextTick so everything is ok).

Thanks for the answer.

Best Regards,
Thomas
