### ISSUE TITLE
Need spy function in assert

### ISSUE THREAD

**Issue by ntvsx193** [thetutlage/japa#9]
I think, good idea, if you are extend original chai of lib as https://github.com/chaijs/chai-spies

```js
expect(spy).to.have.been.called.with('foo');
```

**Comment by thetutlage** [comment]
You can do it inside your project. Spies, Stubs are not something I want bundle by default.

```
const { Assertion } = require('japa/api')
const spies = require('chai-spies')
Assertion.use(spies)
```

If you use `japa-cli` to run tests, then place this code inside `japaFile.js` inside the project root and the cli will load it.

Also note that japa using the `assert` interface of chai, if you want a different interface, simply ditch the japa assert and require chai directly in your test files
